# These are specific configuration settings required for travis-ci
# see http://travis-ci.org/tardate/rgovdata
rvm: 1.9.2
# create test postgresql database
before_script:
  - "psql -c 'create database detached_counter_cache_test;' -U postgres"